### ISSUE TITLE
All links are dead links

### ISSUE THREAD

**Issue by GodTanu** [symbol/symbol-docs#766]
[README.md](https://github.com/symbol/symbol-docs#readme)

Dead link 
https://docs.symbolplatform.com/

Alive
https://docs.symbol.dev/

**Comment by ghost-2014** [comment]
Hey, it looks like everyone does what they want and a lot of things fall by the wayside because there is no proper coordination.
For a better overview, perhaps a link list should be created with the respective official links to the corresponding area. Then links will not be overlooked again and again. 
The fact that the dead link on Github still hasn't been changed after such a long time says a lot about the project. 
Maybe you should reopen the issue.
thx

------

![dead_links](https://user-images.githubusercontent.com/93795770/168266640-38d648c9-d295-4367-a430-07533c44995e.png)

**Comment by 0x6861746366574** [comment]
> Hey, it looks like everyone does what they want and a lot of things fall by the wayside because there is no proper coordination. For a better overview, perhaps a link list should be created with the respective official links to the corresponding area. Then dead links that need to be changed will not be overlooked again and again. The fact that the dead link on Github still hasn't been changed after such a long time says a lot about the project. Maybe you should reopen the issue. thx
> 
> ![dead_links](https://user-images.githubusercontent.com/93795770/168266640-38d648c9-d295-4367-a430-07533c44995e.png)

*Or*, just maybe, you could chip in and update any dead links that you come across instead of being a sassy Santa. If you don't like it, change it. Welcome to crypto, mate.

**Comment by GodTanu** [comment]
Sorry, I don't know how to change that URL. 
So I think I will become a sassy Santa. By the way, I don't even know what sassy Santa is.

Don't I need some authorization to make changes that link?
